from .ltx23_compact_sampler import (
    NODE_CLASS_MAPPINGS as SAMPLER_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as SAMPLER_NODE_DISPLAY_NAME_MAPPINGS,
)
from .ltx23_latent_prompt_nodes import (
    NODE_CLASS_MAPPINGS as LATENT_PROMPT_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as LATENT_PROMPT_NODE_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {
    **SAMPLER_NODE_CLASS_MAPPINGS,
    **LATENT_PROMPT_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **SAMPLER_NODE_DISPLAY_NAME_MAPPINGS,
    **LATENT_PROMPT_NODE_DISPLAY_NAME_MAPPINGS,
}
