"""ComfyUI custom node package entrypoint.

This repository is intended to be cloned into ComfyUI's `custom_nodes` folder
(e.g. `custom_nodes/toobusy`). ComfyUI imports that folder as a Python package,
so this top-level `__init__.py` must expose node mappings.
"""

from .ltx23_compact_sampler_node import (
    NODE_CLASS_MAPPINGS as LTX23_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as LTX23_NODE_DISPLAY_NAME_MAPPINGS,
)
from .keyframe_maker_node import (
    NODE_CLASS_MAPPINGS as KEYFRAME_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as KEYFRAME_NODE_DISPLAY_NAME_MAPPINGS,
)
from .z_image_turbo_node import (
    NODE_CLASS_MAPPINGS as Z_IMAGE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as Z_IMAGE_NODE_DISPLAY_NAME_MAPPINGS,
)
from .storyboard_board_node import (
    NODE_CLASS_MAPPINGS as STORYBOARD_BOARD_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as STORYBOARD_BOARD_NODE_DISPLAY_NAME_MAPPINGS,
)
from .ideogram_layout_builder import (
    NODE_CLASS_MAPPINGS as IDEOGRAM_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as IDEOGRAM_NODE_DISPLAY_NAME_MAPPINGS,
)
from .ideogram4_t2i_node import (
    NODE_CLASS_MAPPINGS as IDEOGRAM4_T2I_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as IDEOGRAM4_T2I_NODE_DISPLAY_NAME_MAPPINGS,
)
from .ideogram_prompt_polish_node import (
    NODE_CLASS_MAPPINGS as PROMPT_POLISH_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as PROMPT_POLISH_NODE_DISPLAY_NAME_MAPPINGS,
)
from .wan_scail_extend_sampler_node import (
    NODE_CLASS_MAPPINGS as WAN_SCAIL_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as WAN_SCAIL_NODE_DISPLAY_NAME_MAPPINGS,
)
from .hires_upscale_node import (
    NODE_CLASS_MAPPINGS as HIRES_UPSCALE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as HIRES_UPSCALE_NODE_DISPLAY_NAME_MAPPINGS,
)
from .zit_controlnet_node import (
    NODE_CLASS_MAPPINGS as ZIT_CONTROLNET_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as ZIT_CONTROLNET_NODE_DISPLAY_NAME_MAPPINGS,
)
from .paint_canvas_node import (
    NODE_CLASS_MAPPINGS as PAINT_CANVAS_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as PAINT_CANVAS_NODE_DISPLAY_NAME_MAPPINGS,
)
from .load_clip_node import (
    NODE_CLASS_MAPPINGS as LOAD_CLIP_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as LOAD_CLIP_NODE_DISPLAY_NAME_MAPPINGS,
)
from .flux2_klein_node import (
    NODE_CLASS_MAPPINGS as FLUX2_KLEIN_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as FLUX2_KLEIN_NODE_DISPLAY_NAME_MAPPINGS,
)
from .image_to_layout_node import (
    NODE_CLASS_MAPPINGS as IMAGE_TO_LAYOUT_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as IMAGE_TO_LAYOUT_NODE_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {
    **LTX23_NODE_CLASS_MAPPINGS,
    **KEYFRAME_NODE_CLASS_MAPPINGS,
    **Z_IMAGE_NODE_CLASS_MAPPINGS,
    **STORYBOARD_BOARD_NODE_CLASS_MAPPINGS,
    **IDEOGRAM_NODE_CLASS_MAPPINGS,
    **IDEOGRAM4_T2I_NODE_CLASS_MAPPINGS,
    **PROMPT_POLISH_NODE_CLASS_MAPPINGS,
    **WAN_SCAIL_NODE_CLASS_MAPPINGS,
    **HIRES_UPSCALE_NODE_CLASS_MAPPINGS,
    **ZIT_CONTROLNET_NODE_CLASS_MAPPINGS,
    **PAINT_CANVAS_NODE_CLASS_MAPPINGS,
    **FLUX2_KLEIN_NODE_CLASS_MAPPINGS,
    **LOAD_CLIP_NODE_CLASS_MAPPINGS,
    **IMAGE_TO_LAYOUT_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **LTX23_NODE_DISPLAY_NAME_MAPPINGS,
    **KEYFRAME_NODE_DISPLAY_NAME_MAPPINGS,
    **Z_IMAGE_NODE_DISPLAY_NAME_MAPPINGS,
    **STORYBOARD_BOARD_NODE_DISPLAY_NAME_MAPPINGS,
    **IDEOGRAM_NODE_DISPLAY_NAME_MAPPINGS,
    **IDEOGRAM4_T2I_NODE_DISPLAY_NAME_MAPPINGS,
    **PROMPT_POLISH_NODE_DISPLAY_NAME_MAPPINGS,
    **WAN_SCAIL_NODE_DISPLAY_NAME_MAPPINGS,
    **HIRES_UPSCALE_NODE_DISPLAY_NAME_MAPPINGS,
    **ZIT_CONTROLNET_NODE_DISPLAY_NAME_MAPPINGS,
    **PAINT_CANVAS_NODE_DISPLAY_NAME_MAPPINGS,
    **FLUX2_KLEIN_NODE_DISPLAY_NAME_MAPPINGS,
    **LOAD_CLIP_NODE_DISPLAY_NAME_MAPPINGS,
    **IMAGE_TO_LAYOUT_NODE_DISPLAY_NAME_MAPPINGS,
}

WEB_DIRECTORY = "./js"
