"""ComfyUI custom node package entrypoint.

This repository is intended to be cloned into ComfyUI's `custom_nodes` folder
(e.g. `custom_nodes/toobusy`). ComfyUI imports that folder as a Python package,
so this top-level `__init__.py` must expose node mappings.
"""

from .ltx23_compact_sampler_node import (
    NODE_CLASS_MAPPINGS as LTX23_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as LTX23_NODE_DISPLAY_NAME_MAPPINGS,
)
from .keyframe_maker_node import (
    NODE_CLASS_MAPPINGS as KEYFRAME_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as KEYFRAME_NODE_DISPLAY_NAME_MAPPINGS,
)
from .z_image_turbo_node import (
    NODE_CLASS_MAPPINGS as Z_IMAGE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as Z_IMAGE_NODE_DISPLAY_NAME_MAPPINGS,
)
from .prompt_lines_node import (
    NODE_CLASS_MAPPINGS as PROMPT_LINES_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as PROMPT_LINES_NODE_DISPLAY_NAME_MAPPINGS,
)
from .storyboard_board_node import (
    NODE_CLASS_MAPPINGS as STORYBOARD_BOARD_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as STORYBOARD_BOARD_NODE_DISPLAY_NAME_MAPPINGS,
)
from .hf_model_auto_loader import (
    NODE_CLASS_MAPPINGS as HF_LOADER_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as HF_LOADER_NODE_DISPLAY_NAME_MAPPINGS,
)
from .ideogram_layout_builder import (
    NODE_CLASS_MAPPINGS as IDEOGRAM_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as IDEOGRAM_NODE_DISPLAY_NAME_MAPPINGS,
)
from .ideogram4_t2i_node import (
    NODE_CLASS_MAPPINGS as IDEOGRAM4_T2I_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as IDEOGRAM4_T2I_NODE_DISPLAY_NAME_MAPPINGS,
)
from .ideogram_prompt_polish_node import (
    NODE_CLASS_MAPPINGS as PROMPT_POLISH_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as PROMPT_POLISH_NODE_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {
    **LTX23_NODE_CLASS_MAPPINGS,
    **KEYFRAME_NODE_CLASS_MAPPINGS,
    **Z_IMAGE_NODE_CLASS_MAPPINGS,
    **PROMPT_LINES_NODE_CLASS_MAPPINGS,
    **STORYBOARD_BOARD_NODE_CLASS_MAPPINGS,
    **HF_LOADER_NODE_CLASS_MAPPINGS,
    **IDEOGRAM_NODE_CLASS_MAPPINGS,
    **IDEOGRAM4_T2I_NODE_CLASS_MAPPINGS,
    **PROMPT_POLISH_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **LTX23_NODE_DISPLAY_NAME_MAPPINGS,
    **KEYFRAME_NODE_DISPLAY_NAME_MAPPINGS,
    **Z_IMAGE_NODE_DISPLAY_NAME_MAPPINGS,
    **PROMPT_LINES_NODE_DISPLAY_NAME_MAPPINGS,
    **STORYBOARD_BOARD_NODE_DISPLAY_NAME_MAPPINGS,
    **HF_LOADER_NODE_DISPLAY_NAME_MAPPINGS,
    **IDEOGRAM_NODE_DISPLAY_NAME_MAPPINGS,
    **IDEOGRAM4_T2I_NODE_DISPLAY_NAME_MAPPINGS,
    **PROMPT_POLISH_NODE_DISPLAY_NAME_MAPPINGS,
}

WEB_DIRECTORY = "./js"
